name = "opensvitlobot"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "opensvitlobot-db"
database_id = "24b99f79-e8a8-4676-b9ee-0de6ca60c9c0"

[vars]
CORS_ORIGIN = "*"
OUTAGE_GROUP = "GPV6.2"
