name = "opensvitlobot"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "opensvitlobot-db"
database_id = "" # Injected by CI

[vars]
CORS_ORIGIN = "*"
OUTAGE_GROUP = "GPV6.2"
